default:
  image:
    name: "pulumi/pulumi:3.129.0"
    entrypoint: [""]

stages:
  - infrastructure-update

pulumi-up:
  stage: infrastructure-update
  before_script:
    - chmod +x ./scripts/*.sh
  script:
    - ./scripts/pulumi-up.sh
  only:
    - main # or master - whatever your default branch is.

pulumi-preview:
  stage: infrastructure-update
  before_script:
    - chmod +x ./scripts/*.sh
  script:
    - ./scripts/pulumi-preview.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
