---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: podinfo
  namespace: podinfo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
