name: pipeline

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if secret exists
        run: |
            if [ -n "${{ secrets.PULUMI_ACCESS_TOKEN }}" ]; then
            echo "Found Pulumi access token. Proceeding with workflow..."
            else
            echo "Pulumi access token does not exist. Aborting workflow..."
            exit 1
            fi
  pulumi-up:
    name: pulumi-up
    needs: check-secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./infra
        run: npm install

      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: diana-pulumi-corp/iac-workshop/test
          work-dir: ./infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
