---
apiVersion: v1
kind: Secret
metadata:
  name: flux-web-config
  namespace: flux-system
stringData:
  config.yaml: |
    apiVersion: web.fluxcd.controlplane.io/v1
    kind: Config
    spec:
      insecure: true
      authentication:
        type: Anonymous
        sessionDuration: 24h
        anonymous:
          username: workshop-user
          groups:
            - flux-web-admin
