// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class KubernetesCluster extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'multi-cloud-kubernetes:index:KubernetesCluster';

    /**
     * Returns true if the given object is an instance of KubernetesCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KubernetesCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KubernetesCluster.__pulumiType;
    }

    declare public readonly clusterName: pulumi.Output<string>;
    declare public /*out*/ readonly endpoint: pulumi.Output<string>;
    declare public /*out*/ readonly kubeconfig: pulumi.Output<string>;

    /**
     * Create a KubernetesCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KubernetesClusterArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.provider === undefined && !opts.urn) {
                throw new Error("Missing required property 'provider'");
            }
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["hubEndpoint"] = args?.hubEndpoint;
            resourceInputs["hubKubeconfig"] = args?.hubKubeconfig;
            resourceInputs["provider"] = args?.provider;
            resourceInputs["region"] = args?.region;
            resourceInputs["role"] = args?.role;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["version"] = args?.version;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
        } else {
            resourceInputs["clusterName"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KubernetesCluster.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a KubernetesCluster resource.
 */
export interface KubernetesClusterArgs {
    clusterName?: pulumi.Input<string>;
    hubEndpoint?: pulumi.Input<string>;
    hubKubeconfig?: pulumi.Input<string>;
    provider: string;
    region?: pulumi.Input<string>;
    role?: string;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    version?: pulumi.Input<string>;
}
