// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AdditionalIpRangesConfigArgs {
    pod_ipv4_range_names?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    subnetwork?: pulumi.Input<string | undefined>;
}

export interface ClusterAutoscalingArgs {
    auto_repair?: pulumi.Input<boolean | undefined>;
    auto_upgrade?: pulumi.Input<boolean | undefined>;
    autoscaling_profile?: pulumi.Input<string | undefined>;
    batch_node_count?: pulumi.Input<number | undefined>;
    batch_percentage?: pulumi.Input<number | undefined>;
    batch_soak_duration?: pulumi.Input<string | undefined>;
    disk_size?: pulumi.Input<number | undefined>;
    disk_type?: pulumi.Input<string | undefined>;
    enable_default_compute_class?: pulumi.Input<boolean | undefined>;
    enable_integrity_monitoring?: pulumi.Input<boolean | undefined>;
    enable_secure_boot?: pulumi.Input<boolean | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    gpu_resources?: pulumi.Input<pulumi.Input<inputs.ClusterAutoscalingGpuResourcesArgs>[] | undefined>;
    image_type?: pulumi.Input<string | undefined>;
    max_cpu_cores?: pulumi.Input<number | undefined>;
    max_memory_gb?: pulumi.Input<number | undefined>;
    max_surge?: pulumi.Input<number | undefined>;
    max_unavailable?: pulumi.Input<number | undefined>;
    min_cpu_cores?: pulumi.Input<number | undefined>;
    min_memory_gb?: pulumi.Input<number | undefined>;
    node_pool_soak_duration?: pulumi.Input<string | undefined>;
    strategy?: pulumi.Input<string | undefined>;
}

export interface ClusterAutoscalingGpuResourcesArgs {
    maximum?: pulumi.Input<number | undefined>;
    minimum?: pulumi.Input<number | undefined>;
    resource_type?: pulumi.Input<string | undefined>;
}

export interface DatabaseEncryptionArgs {
    key_name?: pulumi.Input<string | undefined>;
    state?: pulumi.Input<string | undefined>;
}

export interface MaintenanceExclusionsArgs {
    end_time?: pulumi.Input<string | undefined>;
    exclusion_scope?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    start_time?: pulumi.Input<string | undefined>;
}

export interface MasterAuthorizedNetworksArgs {
    cidr_block?: pulumi.Input<string | undefined>;
    display_name?: pulumi.Input<string | undefined>;
}

export interface NodePoolsTaintsArgs {
    effect?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface RayOperatorConfigArgs {
    enabled?: pulumi.Input<boolean | undefined>;
    logging_enabled?: pulumi.Input<boolean | undefined>;
    monitoring_enabled?: pulumi.Input<boolean | undefined>;
}

export interface RbacBindingConfigArgs {
    enable_insecure_binding_system_authenticated?: pulumi.Input<boolean | undefined>;
    enable_insecure_binding_system_unauthenticated?: pulumi.Input<boolean | undefined>;
}

export interface ShadowFirewallRulesLogConfigArgs {
    metadata?: pulumi.Input<string | undefined>;
}
