apiVersion: v1
kind: Service
metadata:
  name: cat-service
  labels:
    app: cat-app
spec:
  type: LoadBalancer
  selector:
    app: cat-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
