---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: jupyterhub
      version: "4.3.2"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  values:
    hub:
      image:
        name: jupyterhub/k8s-hub
        tag: "4.3.2"
    proxy:
      chp:
        image:
          name: jupyterhub/configurable-http-proxy
          tag: "4.6.3"
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    singleuser:
      defaultUrl: "/lab"
      image:
        name: jupyterhub/k8s-singleuser-sample
        tag: "4.3.2"
      networkTools:
        image:
          name: jupyterhub/k8s-network-tools
          tag: "4.3.2"
    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: false
    scheduling:
      userScheduler:
        enabled: false
