---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: jupyterhub
      version: "5.4.4"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  values:
    proxy:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    singleuser:
      defaultUrl: "/lab"
