// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Module extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'gke:index:Module';

    /**
     * Returns true if the given object is an instance of Module.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Module {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Module.__pulumiType;
    }

    /**
     * Cluster ca certificate (base64 encoded)
     */
    declare public /*out*/ readonly ca_certificate: pulumi.Output<string | undefined>;
    /**
     * Cluster ID
     */
    declare public /*out*/ readonly cluster_id: pulumi.Output<string | undefined>;
    /**
     * Whether DNS Cache enabled
     */
    declare public /*out*/ readonly dns_cache_enabled: pulumi.Output<string | undefined>;
    /**
     * Cluster endpoint
     */
    declare public /*out*/ readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * Cluster endpoint DNS
     */
    declare public /*out*/ readonly endpoint_dns: pulumi.Output<string | undefined>;
    /**
     * Fleet membership (if registered)
     */
    declare public /*out*/ readonly fleet_membership: pulumi.Output<string | undefined>;
    /**
     * The gateway api channel of this cluster.
     */
    declare public readonly gateway_api_channel: pulumi.Output<string | undefined>;
    /**
     * Whether horizontal pod autoscaling enabled
     */
    declare public /*out*/ readonly horizontal_pod_autoscaling_enabled: pulumi.Output<string | undefined>;
    /**
     * Whether http load balancing enabled
     */
    declare public /*out*/ readonly http_load_balancing_enabled: pulumi.Output<string | undefined>;
    /**
     * Workload Identity pool
     */
    declare public readonly identity_namespace: pulumi.Output<string | undefined>;
    /**
     * Whether Identity Service is enabled
     */
    declare public /*out*/ readonly identity_service_enabled: pulumi.Output<string | undefined>;
    /**
     * List of GKE generated instance groups
     */
    declare public /*out*/ readonly instance_group_urls: pulumi.Output<string | undefined>;
    /**
     * Whether intra-node visibility is enabled
     */
    declare public /*out*/ readonly intranode_visibility_enabled: pulumi.Output<string | undefined>;
    /**
     * Cluster location (region if regional cluster, zone if zonal cluster)
     */
    declare public /*out*/ readonly location: pulumi.Output<string | undefined>;
    /**
     * Logging service used
     */
    declare public readonly logging_service: pulumi.Output<string | undefined>;
    /**
     * Networks from which access to master is permitted
     */
    declare public /*out*/ readonly master_authorized_networks_config: pulumi.Output<string | undefined>;
    /**
     * The IP range in CIDR notation used for the hosted master network
     */
    declare public readonly master_ipv4_cidr_block: pulumi.Output<string | undefined>;
    /**
     * Current master kubernetes version
     */
    declare public /*out*/ readonly master_version: pulumi.Output<string | undefined>;
    /**
     * Mesh certificates configuration
     */
    declare public /*out*/ readonly mesh_certificates_config: pulumi.Output<string | undefined>;
    /**
     * Minimum master kubernetes version
     */
    declare public /*out*/ readonly min_master_version: pulumi.Output<string | undefined>;
    /**
     * Monitoring service used
     */
    declare public readonly monitoring_service: pulumi.Output<string | undefined>;
    /**
     * Cluster name
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * Whether network policy enabled
     */
    declare public /*out*/ readonly network_policy_enabled: pulumi.Output<string | undefined>;
    /**
     * List of node pools names
     */
    declare public /*out*/ readonly node_pools_names: pulumi.Output<string | undefined>;
    /**
     * Node pool versions by node pool name
     */
    declare public /*out*/ readonly node_pools_versions: pulumi.Output<string | undefined>;
    /**
     * The name of the peering between this cluster and the Google owned VPC.
     */
    declare public /*out*/ readonly peering_name: pulumi.Output<string | undefined>;
    /**
     * Cluster region
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * The release channel of this cluster
     */
    declare public readonly release_channel: pulumi.Output<string | undefined>;
    /**
     * Whether Secret Manager add-on is enabled
     */
    declare public /*out*/ readonly secret_manager_addon_enabled: pulumi.Output<string | undefined>;
    /**
     * The service account to default running nodes as if not overridden in `node_pools`.
     */
    declare public readonly service_account: pulumi.Output<string | undefined>;
    /**
     * The IP range in CIDR notation used for the TPUs
     */
    declare public /*out*/ readonly tpu_ipv4_cidr_block: pulumi.Output<string | undefined>;
    /**
     * Cluster type (regional / zonal)
     */
    declare public /*out*/ readonly type: pulumi.Output<string | undefined>;
    /**
     * Whether vertical pod autoscaling enabled
     */
    declare public /*out*/ readonly vertical_pod_autoscaling_enabled: pulumi.Output<string | undefined>;
    /**
     * List of zones in which the cluster resides
     */
    declare public readonly zones: pulumi.Output<string | undefined>;

    /**
     * Create a Module resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ModuleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["add_cluster_firewall_rules"] = args?.add_cluster_firewall_rules;
            resourceInputs["add_master_webhook_firewall_rules"] = args?.add_master_webhook_firewall_rules;
            resourceInputs["add_shadow_firewall_rules"] = args?.add_shadow_firewall_rules;
            resourceInputs["additional_ip_range_pods"] = args?.additional_ip_range_pods;
            resourceInputs["additional_ip_ranges_config"] = args?.additional_ip_ranges_config;
            resourceInputs["additive_vpc_scope_dns_domain"] = args?.additive_vpc_scope_dns_domain;
            resourceInputs["anonymous_authentication_config_mode"] = args?.anonymous_authentication_config_mode;
            resourceInputs["authenticator_security_group"] = args?.authenticator_security_group;
            resourceInputs["boot_disk_kms_key"] = args?.boot_disk_kms_key;
            resourceInputs["cluster_autoscaling"] = args?.cluster_autoscaling;
            resourceInputs["cluster_dns_domain"] = args?.cluster_dns_domain;
            resourceInputs["cluster_dns_provider"] = args?.cluster_dns_provider;
            resourceInputs["cluster_dns_scope"] = args?.cluster_dns_scope;
            resourceInputs["cluster_ipv4_cidr"] = args?.cluster_ipv4_cidr;
            resourceInputs["cluster_resource_labels"] = args?.cluster_resource_labels;
            resourceInputs["config_connector"] = args?.config_connector;
            resourceInputs["configure_ip_masq"] = args?.configure_ip_masq;
            resourceInputs["create_service_account"] = args?.create_service_account;
            resourceInputs["database_encryption"] = args?.database_encryption;
            resourceInputs["datapath_provider"] = args?.datapath_provider;
            resourceInputs["default_max_pods_per_node"] = args?.default_max_pods_per_node;
            resourceInputs["deletion_protection"] = args?.deletion_protection;
            resourceInputs["deploy_using_private_endpoint"] = args?.deploy_using_private_endpoint;
            resourceInputs["description"] = args?.description;
            resourceInputs["disable_default_snat"] = args?.disable_default_snat;
            resourceInputs["disable_l4_lb_firewall_reconciliation"] = args?.disable_l4_lb_firewall_reconciliation;
            resourceInputs["disable_legacy_metadata_endpoints"] = args?.disable_legacy_metadata_endpoints;
            resourceInputs["dns_allow_external_traffic"] = args?.dns_allow_external_traffic;
            resourceInputs["dns_cache"] = args?.dns_cache;
            resourceInputs["enable_binary_authorization"] = args?.enable_binary_authorization;
            resourceInputs["enable_cilium_clusterwide_network_policy"] = args?.enable_cilium_clusterwide_network_policy;
            resourceInputs["enable_confidential_nodes"] = args?.enable_confidential_nodes;
            resourceInputs["enable_cost_allocation"] = args?.enable_cost_allocation;
            resourceInputs["enable_default_node_pools_metadata"] = args?.enable_default_node_pools_metadata;
            resourceInputs["enable_fqdn_network_policy"] = args?.enable_fqdn_network_policy;
            resourceInputs["enable_gcfs"] = args?.enable_gcfs;
            resourceInputs["enable_identity_service"] = args?.enable_identity_service;
            resourceInputs["enable_intranode_visibility"] = args?.enable_intranode_visibility;
            resourceInputs["enable_k8s_beta_apis"] = args?.enable_k8s_beta_apis;
            resourceInputs["enable_kubernetes_alpha"] = args?.enable_kubernetes_alpha;
            resourceInputs["enable_l4_ilb_subsetting"] = args?.enable_l4_ilb_subsetting;
            resourceInputs["enable_legacy_lustre_port"] = args?.enable_legacy_lustre_port;
            resourceInputs["enable_mesh_certificates"] = args?.enable_mesh_certificates;
            resourceInputs["enable_multi_networking"] = args?.enable_multi_networking;
            resourceInputs["enable_network_egress_export"] = args?.enable_network_egress_export;
            resourceInputs["enable_private_endpoint"] = args?.enable_private_endpoint;
            resourceInputs["enable_private_nodes"] = args?.enable_private_nodes;
            resourceInputs["enable_resource_consumption_export"] = args?.enable_resource_consumption_export;
            resourceInputs["enable_secret_manager_addon"] = args?.enable_secret_manager_addon;
            resourceInputs["enable_shielded_nodes"] = args?.enable_shielded_nodes;
            resourceInputs["enable_tpu"] = args?.enable_tpu;
            resourceInputs["enable_vertical_pod_autoscaling"] = args?.enable_vertical_pod_autoscaling;
            resourceInputs["enterprise_config"] = args?.enterprise_config;
            resourceInputs["filestore_csi_driver"] = args?.filestore_csi_driver;
            resourceInputs["firewall_inbound_ports"] = args?.firewall_inbound_ports;
            resourceInputs["firewall_priority"] = args?.firewall_priority;
            resourceInputs["fleet_project"] = args?.fleet_project;
            resourceInputs["gateway_api_channel"] = args?.gateway_api_channel;
            resourceInputs["gce_pd_csi_driver"] = args?.gce_pd_csi_driver;
            resourceInputs["gcp_public_cidrs_access_enabled"] = args?.gcp_public_cidrs_access_enabled;
            resourceInputs["gcs_fuse_csi_driver"] = args?.gcs_fuse_csi_driver;
            resourceInputs["gke_auto_upgrade_config_patch_mode"] = args?.gke_auto_upgrade_config_patch_mode;
            resourceInputs["gke_backup_agent_config"] = args?.gke_backup_agent_config;
            resourceInputs["grant_registry_access"] = args?.grant_registry_access;
            resourceInputs["horizontal_pod_autoscaling"] = args?.horizontal_pod_autoscaling;
            resourceInputs["hpa_profile"] = args?.hpa_profile;
            resourceInputs["http_load_balancing"] = args?.http_load_balancing;
            resourceInputs["identity_namespace"] = args?.identity_namespace;
            resourceInputs["in_transit_encryption_config"] = args?.in_transit_encryption_config;
            resourceInputs["initial_node_count"] = args?.initial_node_count;
            resourceInputs["insecure_kubelet_readonly_port_enabled"] = args?.insecure_kubelet_readonly_port_enabled;
            resourceInputs["ip_endpoints_enabled"] = args?.ip_endpoints_enabled;
            resourceInputs["ip_masq_link_local"] = args?.ip_masq_link_local;
            resourceInputs["ip_masq_resync_interval"] = args?.ip_masq_resync_interval;
            resourceInputs["ip_range_pods"] = args?.ip_range_pods;
            resourceInputs["ip_range_services"] = args?.ip_range_services;
            resourceInputs["issue_client_certificate"] = args?.issue_client_certificate;
            resourceInputs["kubernetes_version"] = args?.kubernetes_version;
            resourceInputs["logging_enabled_components"] = args?.logging_enabled_components;
            resourceInputs["logging_service"] = args?.logging_service;
            resourceInputs["logging_variant"] = args?.logging_variant;
            resourceInputs["lustre_csi_driver"] = args?.lustre_csi_driver;
            resourceInputs["maintenance_end_time"] = args?.maintenance_end_time;
            resourceInputs["maintenance_exclusions"] = args?.maintenance_exclusions;
            resourceInputs["maintenance_recurrence"] = args?.maintenance_recurrence;
            resourceInputs["maintenance_start_time"] = args?.maintenance_start_time;
            resourceInputs["master_authorized_networks"] = args?.master_authorized_networks;
            resourceInputs["master_global_access_enabled"] = args?.master_global_access_enabled;
            resourceInputs["master_ipv4_cidr_block"] = args?.master_ipv4_cidr_block;
            resourceInputs["monitoring_auto_monitoring_config_scope"] = args?.monitoring_auto_monitoring_config_scope;
            resourceInputs["monitoring_enable_managed_prometheus"] = args?.monitoring_enable_managed_prometheus;
            resourceInputs["monitoring_enable_observability_metrics"] = args?.monitoring_enable_observability_metrics;
            resourceInputs["monitoring_enable_observability_relay"] = args?.monitoring_enable_observability_relay;
            resourceInputs["monitoring_enabled_components"] = args?.monitoring_enabled_components;
            resourceInputs["monitoring_metric_writer_role"] = args?.monitoring_metric_writer_role;
            resourceInputs["monitoring_service"] = args?.monitoring_service;
            resourceInputs["name"] = args?.name;
            resourceInputs["network"] = args?.network;
            resourceInputs["network_policy"] = args?.network_policy;
            resourceInputs["network_policy_provider"] = args?.network_policy_provider;
            resourceInputs["network_project_id"] = args?.network_project_id;
            resourceInputs["network_tags"] = args?.network_tags;
            resourceInputs["network_tier_config"] = args?.network_tier_config;
            resourceInputs["node_metadata"] = args?.node_metadata;
            resourceInputs["node_pools"] = args?.node_pools;
            resourceInputs["node_pools_cgroup_mode"] = args?.node_pools_cgroup_mode;
            resourceInputs["node_pools_hugepage_size_1g"] = args?.node_pools_hugepage_size_1g;
            resourceInputs["node_pools_hugepage_size_2m"] = args?.node_pools_hugepage_size_2m;
            resourceInputs["node_pools_labels"] = args?.node_pools_labels;
            resourceInputs["node_pools_linux_node_configs_sysctls"] = args?.node_pools_linux_node_configs_sysctls;
            resourceInputs["node_pools_metadata"] = args?.node_pools_metadata;
            resourceInputs["node_pools_oauth_scopes"] = args?.node_pools_oauth_scopes;
            resourceInputs["node_pools_resource_labels"] = args?.node_pools_resource_labels;
            resourceInputs["node_pools_resource_manager_tags"] = args?.node_pools_resource_manager_tags;
            resourceInputs["node_pools_tags"] = args?.node_pools_tags;
            resourceInputs["node_pools_taints"] = args?.node_pools_taints;
            resourceInputs["node_pools_transparent_hugepage_defrag"] = args?.node_pools_transparent_hugepage_defrag;
            resourceInputs["node_pools_transparent_hugepage_enabled"] = args?.node_pools_transparent_hugepage_enabled;
            resourceInputs["non_masquerade_cidrs"] = args?.non_masquerade_cidrs;
            resourceInputs["notification_config_topic"] = args?.notification_config_topic;
            resourceInputs["notification_filter_event_type"] = args?.notification_filter_event_type;
            resourceInputs["parallelstore_csi_driver"] = args?.parallelstore_csi_driver;
            resourceInputs["private_endpoint_subnetwork"] = args?.private_endpoint_subnetwork;
            resourceInputs["project_id"] = args?.project_id;
            resourceInputs["ray_operator_config"] = args?.ray_operator_config;
            resourceInputs["rbac_binding_config"] = args?.rbac_binding_config;
            resourceInputs["region"] = args?.region;
            resourceInputs["regional"] = args?.regional;
            resourceInputs["registry_project_ids"] = args?.registry_project_ids;
            resourceInputs["release_channel"] = args?.release_channel;
            resourceInputs["remove_default_node_pool"] = args?.remove_default_node_pool;
            resourceInputs["resource_manager_tags"] = args?.resource_manager_tags;
            resourceInputs["resource_usage_export_dataset_id"] = args?.resource_usage_export_dataset_id;
            resourceInputs["security_posture_mode"] = args?.security_posture_mode;
            resourceInputs["security_posture_vulnerability_mode"] = args?.security_posture_vulnerability_mode;
            resourceInputs["service_account"] = args?.service_account;
            resourceInputs["service_account_name"] = args?.service_account_name;
            resourceInputs["service_external_ips"] = args?.service_external_ips;
            resourceInputs["shadow_firewall_rules_log_config"] = args?.shadow_firewall_rules_log_config;
            resourceInputs["shadow_firewall_rules_priority"] = args?.shadow_firewall_rules_priority;
            resourceInputs["stack_type"] = args?.stack_type;
            resourceInputs["stateful_ha"] = args?.stateful_ha;
            resourceInputs["stub_domains"] = args?.stub_domains;
            resourceInputs["subnetwork"] = args?.subnetwork;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["total_egress_bandwidth_tier"] = args?.total_egress_bandwidth_tier;
            resourceInputs["upstream_nameservers"] = args?.upstream_nameservers;
            resourceInputs["windows_node_pools"] = args?.windows_node_pools;
            resourceInputs["zones"] = args?.zones;
            resourceInputs["ca_certificate"] = undefined /*out*/;
            resourceInputs["cluster_id"] = undefined /*out*/;
            resourceInputs["dns_cache_enabled"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["endpoint_dns"] = undefined /*out*/;
            resourceInputs["fleet_membership"] = undefined /*out*/;
            resourceInputs["horizontal_pod_autoscaling_enabled"] = undefined /*out*/;
            resourceInputs["http_load_balancing_enabled"] = undefined /*out*/;
            resourceInputs["identity_service_enabled"] = undefined /*out*/;
            resourceInputs["instance_group_urls"] = undefined /*out*/;
            resourceInputs["intranode_visibility_enabled"] = undefined /*out*/;
            resourceInputs["location"] = undefined /*out*/;
            resourceInputs["master_authorized_networks_config"] = undefined /*out*/;
            resourceInputs["master_version"] = undefined /*out*/;
            resourceInputs["mesh_certificates_config"] = undefined /*out*/;
            resourceInputs["min_master_version"] = undefined /*out*/;
            resourceInputs["network_policy_enabled"] = undefined /*out*/;
            resourceInputs["node_pools_names"] = undefined /*out*/;
            resourceInputs["node_pools_versions"] = undefined /*out*/;
            resourceInputs["peering_name"] = undefined /*out*/;
            resourceInputs["secret_manager_addon_enabled"] = undefined /*out*/;
            resourceInputs["tpu_ipv4_cidr_block"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["vertical_pod_autoscaling_enabled"] = undefined /*out*/;
        } else {
            resourceInputs["ca_certificate"] = undefined /*out*/;
            resourceInputs["cluster_id"] = undefined /*out*/;
            resourceInputs["dns_cache_enabled"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["endpoint_dns"] = undefined /*out*/;
            resourceInputs["fleet_membership"] = undefined /*out*/;
            resourceInputs["gateway_api_channel"] = undefined /*out*/;
            resourceInputs["horizontal_pod_autoscaling_enabled"] = undefined /*out*/;
            resourceInputs["http_load_balancing_enabled"] = undefined /*out*/;
            resourceInputs["identity_namespace"] = undefined /*out*/;
            resourceInputs["identity_service_enabled"] = undefined /*out*/;
            resourceInputs["instance_group_urls"] = undefined /*out*/;
            resourceInputs["intranode_visibility_enabled"] = undefined /*out*/;
            resourceInputs["location"] = undefined /*out*/;
            resourceInputs["logging_service"] = undefined /*out*/;
            resourceInputs["master_authorized_networks_config"] = undefined /*out*/;
            resourceInputs["master_ipv4_cidr_block"] = undefined /*out*/;
            resourceInputs["master_version"] = undefined /*out*/;
            resourceInputs["mesh_certificates_config"] = undefined /*out*/;
            resourceInputs["min_master_version"] = undefined /*out*/;
            resourceInputs["monitoring_service"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["network_policy_enabled"] = undefined /*out*/;
            resourceInputs["node_pools_names"] = undefined /*out*/;
            resourceInputs["node_pools_versions"] = undefined /*out*/;
            resourceInputs["peering_name"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["release_channel"] = undefined /*out*/;
            resourceInputs["secret_manager_addon_enabled"] = undefined /*out*/;
            resourceInputs["service_account"] = undefined /*out*/;
            resourceInputs["tpu_ipv4_cidr_block"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["vertical_pod_autoscaling_enabled"] = undefined /*out*/;
            resourceInputs["zones"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["ca_certificate", "endpoint"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Module.__pulumiType, name, resourceInputs, opts, true /*remote*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Module resource.
 */
export interface ModuleArgs {
    /**
     * Create additional firewall rules
     */
    add_cluster_firewall_rules?: pulumi.Input<boolean | undefined>;
    /**
     * Create master_webhook firewall rules for ports defined in `firewall_inbound_ports`
     */
    add_master_webhook_firewall_rules?: pulumi.Input<boolean | undefined>;
    /**
     * Create GKE shadow firewall (the same as default firewall rules with firewall logs enabled).
     */
    add_shadow_firewall_rules?: pulumi.Input<boolean | undefined>;
    /**
     * List of _names_ of the additional secondary subnet ip ranges to use for pods
     */
    additional_ip_range_pods?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * the configuration for individual additional subnetworks attached to the cluster
     */
    additional_ip_ranges_config?: pulumi.Input<pulumi.Input<inputs.AdditionalIpRangesConfigArgs>[] | undefined>;
    /**
     * This will enable Cloud DNS additive VPC scope. Must provide a domain name that is unique within the VPC. For this to work cluster_dns = `CLOUD_DNS` and cluster_dns_scope = `CLUSTER_SCOPE` must both be set as well.
     */
    additive_vpc_scope_dns_domain?: pulumi.Input<string | undefined>;
    /**
     * Allows users to restrict or enable anonymous access to the cluster. Valid values are `ENABLED` and `LIMITED`.
     */
    anonymous_authentication_config_mode?: pulumi.Input<string | undefined>;
    /**
     * The name of the RBAC security group for use with Google security groups in Kubernetes RBAC. Group name must be in format gke-security-groups@yourdomain.com
     */
    authenticator_security_group?: pulumi.Input<string | undefined>;
    /**
     * The Customer Managed Encryption Key used to encrypt the boot disk attached to each node in the node pool, if not overridden in `node_pools`. This should be of the form projects/[KEY_PROJECT_ID]/locations/[LOCATION]/keyRings/[RING_NAME]/cryptoKeys/[KEY_NAME]. For more information about protecting resources with Cloud KMS Keys please see: https://cloud.google.com/compute/docs/disks/customer-managed-encryption
     */
    boot_disk_kms_key?: pulumi.Input<string | undefined>;
    /**
     * Cluster autoscaling configuration. See [more details](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#clusterautoscaling)
     */
    cluster_autoscaling?: pulumi.Input<inputs.ClusterAutoscalingArgs | undefined>;
    /**
     * The suffix used for all cluster service records.
     */
    cluster_dns_domain?: pulumi.Input<string | undefined>;
    /**
     * Which in-cluster DNS provider should be used. PROVIDER_UNSPECIFIED (default) or PLATFORM_DEFAULT or CLOUD_DNS.
     */
    cluster_dns_provider?: pulumi.Input<string | undefined>;
    /**
     * The scope of access to cluster DNS records. DNS_SCOPE_UNSPECIFIED (default) or CLUSTER_SCOPE or VPC_SCOPE. 
     */
    cluster_dns_scope?: pulumi.Input<string | undefined>;
    /**
     * The IP address range of the kubernetes pods in this cluster. Default is an automatically assigned CIDR.
     */
    cluster_ipv4_cidr?: pulumi.Input<string | undefined>;
    /**
     * The GCE resource labels (a map of key/value pairs) to be applied to the cluster
     */
    cluster_resource_labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Whether ConfigConnector is enabled for this cluster.
     */
    config_connector?: pulumi.Input<boolean | undefined>;
    /**
     * Enables the installation of ip masquerading, which is usually no longer required when using aliasied IP addresses. IP masquerading uses a kubectl call, so when you have a private cluster, you will need access to the API server.
     */
    configure_ip_masq?: pulumi.Input<boolean | undefined>;
    /**
     * Defines if service account specified to run nodes should be created.
     */
    create_service_account?: pulumi.Input<boolean | undefined>;
    /**
     * Application-layer Secrets Encryption settings. The object format is {state = string, key_name = string}. Valid values of state are: "ENCRYPTED"; "DECRYPTED". key_name is the name of a CloudKMS key.
     */
    database_encryption?: pulumi.Input<pulumi.Input<inputs.DatabaseEncryptionArgs>[] | undefined>;
    /**
     * The desired datapath provider for this cluster. By default, `DATAPATH_PROVIDER_UNSPECIFIED` enables the IPTables-based kube-proxy implementation. `ADVANCED_DATAPATH` enables Dataplane-V2 feature.
     */
    datapath_provider?: pulumi.Input<string | undefined>;
    /**
     * The maximum number of pods to schedule per node
     */
    default_max_pods_per_node?: pulumi.Input<number | undefined>;
    /**
     * Whether or not to allow Terraform to destroy the cluster.
     */
    deletion_protection?: pulumi.Input<boolean | undefined>;
    /**
     * A toggle for Terraform and kubectl to connect to the master's internal IP address during deployment.
     */
    deploy_using_private_endpoint?: pulumi.Input<boolean | undefined>;
    /**
     * The description of the cluster
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether to disable the default SNAT to support the private use of public IP addresses
     */
    disable_default_snat?: pulumi.Input<boolean | undefined>;
    /**
     * Disable L4 Load Balancer firewall reconciliation
     */
    disable_l4_lb_firewall_reconciliation?: pulumi.Input<boolean | undefined>;
    /**
     * Disable the /0.1/ and /v1beta1/ metadata server endpoints on the node. Changing this value will cause all node pools to be recreated.
     */
    disable_legacy_metadata_endpoints?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) Controls whether external traffic is allowed over the dns endpoint.
     */
    dns_allow_external_traffic?: pulumi.Input<boolean | undefined>;
    /**
     * The status of the NodeLocal DNSCache addon.
     */
    dns_cache?: pulumi.Input<boolean | undefined>;
    /**
     * Enable BinAuthZ Admission controller
     */
    enable_binary_authorization?: pulumi.Input<boolean | undefined>;
    /**
     * Enable Cilium Cluster Wide Network Policies on the cluster
     */
    enable_cilium_clusterwide_network_policy?: pulumi.Input<boolean | undefined>;
    /**
     * An optional flag to enable confidential node config.
     */
    enable_confidential_nodes?: pulumi.Input<boolean | undefined>;
    /**
     * Enables Cost Allocation Feature and the cluster name and namespace of your GKE workloads appear in the labels field of the billing export to BigQuery
     */
    enable_cost_allocation?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to enable the default node pools metadata key-value pairs such as `cluster_name` and `node_pool`
     */
    enable_default_node_pools_metadata?: pulumi.Input<boolean | undefined>;
    /**
     * Enable FQDN Network Policies on the cluster
     */
    enable_fqdn_network_policy?: pulumi.Input<boolean | undefined>;
    /**
     * Enable image streaming on cluster level.
     */
    enable_gcfs?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) Enable the Identity Service component, which allows customers to use external identity providers with the K8S API. NOTE: Starting on July 1, 2025, new Google Cloud organizations that you create won't support Identity Service for GKE.
     */
    enable_identity_service?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Intra-node visibility is enabled for this cluster. This makes same node pod to pod traffic visible for VPC network
     */
    enable_intranode_visibility?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) - List of Kubernetes Beta APIs to enable in cluster.
     */
    enable_k8s_beta_apis?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to enable Kubernetes Alpha features for this cluster. Note that when this option is enabled, the cluster cannot be upgraded and will be automatically deleted after 30 days.
     */
    enable_kubernetes_alpha?: pulumi.Input<boolean | undefined>;
    /**
     * Enable L4 ILB Subsetting on the cluster
     */
    enable_l4_ilb_subsetting?: pulumi.Input<boolean | undefined>;
    /**
     * Set it to true for GKE cluster runs a version earlier than 1.33.2-gke.4780000. Allows the Lustre CSI driver to initialize LNet (the virtual network layer for Lustre kernel module) using port 6988. This flag is required to workaround a port conflict with the gke-metadata-server on GKE nodes
     */
    enable_legacy_lustre_port?: pulumi.Input<boolean | undefined>;
    /**
     * Controls the issuance of workload mTLS certificates. When enabled the GKE Workload Identity Certificates controller and node agent will be deployed in the cluster. Requires Workload Identity.
     */
    enable_mesh_certificates?: pulumi.Input<boolean | undefined>;
    /**
     * Whether multi-networking is enabled for this cluster
     */
    enable_multi_networking?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to enable network egress metering for this cluster. If enabled, a daemonset will be created in the cluster to meter network egress traffic.
     */
    enable_network_egress_export?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the master's internal IP address is used as the cluster endpoint
     */
    enable_private_endpoint?: pulumi.Input<boolean | undefined>;
    /**
     * Whether nodes have internal IP addresses only
     */
    enable_private_nodes?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to enable resource consumption metering on this cluster. When enabled, a table will be created in the resource export BigQuery dataset to store resource consumption data. The resulting table can be joined with the resource usage table or with BigQuery billing export.
     */
    enable_resource_consumption_export?: pulumi.Input<boolean | undefined>;
    /**
     * Enable the Secret Manager add-on for this cluster
     */
    enable_secret_manager_addon?: pulumi.Input<boolean | undefined>;
    /**
     * Enable Shielded Nodes features on all nodes in this cluster
     */
    enable_shielded_nodes?: pulumi.Input<boolean | undefined>;
    /**
     * Enable Cloud TPU resources in the cluster. WARNING: changing this after cluster creation is destructive!
     */
    enable_tpu?: pulumi.Input<boolean | undefined>;
    /**
     * Vertical Pod Autoscaling automatically adjusts the resources of pods controlled by it
     */
    enable_vertical_pod_autoscaling?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) Enable or disable GKE enterprise. Valid values are STANDARD and ENTERPRISE.
     */
    enterprise_config?: pulumi.Input<string | undefined>;
    /**
     * The status of the Filestore CSI driver addon, which allows the usage of filestore instance as volumes
     */
    filestore_csi_driver?: pulumi.Input<boolean | undefined>;
    /**
     * List of TCP ports for admission/webhook controllers. Either flag `add_master_webhook_firewall_rules` or `add_cluster_firewall_rules` (also adds egress rules) must be set to `true` for inbound-ports firewall rules to be applied.
     */
    firewall_inbound_ports?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Priority rule for firewall rules
     */
    firewall_priority?: pulumi.Input<number | undefined>;
    /**
     * (Optional) Register the cluster with the fleet in this project.
     */
    fleet_project?: pulumi.Input<string | undefined>;
    /**
     * The gateway api channel of this cluster. Accepted values are `CHANNEL_STANDARD` and `CHANNEL_DISABLED`.
     */
    gateway_api_channel?: pulumi.Input<string | undefined>;
    /**
     * Whether this cluster should enable the Google Compute Engine Persistent Disk Container Storage Interface (CSI) Driver.
     */
    gce_pd_csi_driver?: pulumi.Input<boolean | undefined>;
    /**
     * Allow access through Google Cloud public IP addresses
     */
    gcp_public_cidrs_access_enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether GCE FUSE CSI driver is enabled for this cluster.
     */
    gcs_fuse_csi_driver?: pulumi.Input<boolean | undefined>;
    /**
     * The selected auto-upgrade patch type. Accepted values are: `ACCELERATED`: Upgrades to the latest available patch version in a given minor and release channel.
     */
    gke_auto_upgrade_config_patch_mode?: pulumi.Input<string | undefined>;
    /**
     * Whether Backup for GKE agent is enabled for this cluster.
     */
    gke_backup_agent_config?: pulumi.Input<boolean | undefined>;
    /**
     * Grants created cluster-specific service account storage.objectViewer and artifactregistry.reader roles.
     */
    grant_registry_access?: pulumi.Input<boolean | undefined>;
    /**
     * Enable horizontal pod autoscaling addon
     */
    horizontal_pod_autoscaling?: pulumi.Input<boolean | undefined>;
    /**
     * Enable the Horizontal Pod Autoscaling profile for this cluster. Values are "NONE" and "PERFORMANCE".
     */
    hpa_profile?: pulumi.Input<string | undefined>;
    /**
     * Enable httpload balancer addon
     */
    http_load_balancing?: pulumi.Input<boolean | undefined>;
    /**
     * The workload pool to attach all Kubernetes service accounts to. (Default value of `enabled` automatically sets project-based pool `[project_id].svc.id.goog`)
     */
    identity_namespace?: pulumi.Input<string | undefined>;
    /**
     * Defines the config of in-transit encryption. Valid values are `IN_TRANSIT_ENCRYPTION_DISABLED` and `IN_TRANSIT_ENCRYPTION_INTER_NODE_TRANSPARENT`.
     */
    in_transit_encryption_config?: pulumi.Input<string | undefined>;
    /**
     * The number of nodes to create in this cluster's default node pool.
     */
    initial_node_count?: pulumi.Input<number | undefined>;
    /**
     * Whether or not to set `insecure_kubelet_readonly_port_enabled` for node pool defaults and autopilot clusters. Note: this can be set at the node pool level separately within `node_pools`.
     */
    insecure_kubelet_readonly_port_enabled?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) Controls whether to allow direct IP access. Defaults to `true`.
     */
    ip_endpoints_enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to masquerade traffic to the link-local prefix (169.254.0.0/16).
     */
    ip_masq_link_local?: pulumi.Input<boolean | undefined>;
    /**
     * The interval at which the agent attempts to sync its ConfigMap file from the disk.
     */
    ip_masq_resync_interval?: pulumi.Input<string | undefined>;
    /**
     * The _name_ of the secondary subnet ip range to use for pods
     */
    ip_range_pods?: pulumi.Input<string | undefined>;
    /**
     * The _name_ of the secondary subnet range to use for services. If not provided, the default `34.118.224.0/20` range will be used.
     */
    ip_range_services?: pulumi.Input<string | undefined>;
    /**
     * Issues a client certificate to authenticate to the cluster endpoint. To maximize the security of your cluster, leave this option disabled. Client certificates don't automatically rotate and aren't easily revocable. WARNING: changing this after cluster creation is destructive!
     */
    issue_client_certificate?: pulumi.Input<boolean | undefined>;
    /**
     * The Kubernetes version of the masters. If set to 'latest' it will pull latest available version in the selected region.
     */
    kubernetes_version?: pulumi.Input<string | undefined>;
    /**
     * List of services to monitor: SYSTEM_COMPONENTS, APISERVER, CONTROLLER_MANAGER, KCP_CONNECTION, KCP_SSHD, KCP_HPA, SCHEDULER, and WORKLOADS. Empty list is default GKE configuration.
     */
    logging_enabled_components?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The logging service that the cluster should write logs to. Available options include logging.googleapis.com, logging.googleapis.com/kubernetes (beta), and none
     */
    logging_service?: pulumi.Input<string | undefined>;
    /**
     * (Optional) The type of logging agent that is deployed by default for newly created node pools in the cluster. Valid values include DEFAULT and MAX_THROUGHPUT.
     */
    logging_variant?: pulumi.Input<string | undefined>;
    /**
     * The status of the Lustre CSI driver addon, which allows the usage of a Lustre instances as volumes
     */
    lustre_csi_driver?: pulumi.Input<boolean | undefined>;
    /**
     * Time window specified for recurring maintenance operations in RFC3339 format
     */
    maintenance_end_time?: pulumi.Input<string | undefined>;
    /**
     * List of maintenance exclusions. A cluster can have up to three
     */
    maintenance_exclusions?: pulumi.Input<pulumi.Input<inputs.MaintenanceExclusionsArgs>[] | undefined>;
    /**
     * Frequency of the recurring maintenance window in RFC5545 format.
     */
    maintenance_recurrence?: pulumi.Input<string | undefined>;
    /**
     * Time window specified for daily or recurring maintenance operations in RFC3339 format
     */
    maintenance_start_time?: pulumi.Input<string | undefined>;
    /**
     * List of master authorized networks. If none are provided, disallow external access (except the cluster node IPs, which GKE automatically whitelists).
     */
    master_authorized_networks?: pulumi.Input<pulumi.Input<inputs.MasterAuthorizedNetworksArgs>[] | undefined>;
    /**
     * Whether the cluster master is accessible globally (from any region) or only within the same region as the private endpoint.
     */
    master_global_access_enabled?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) The IP range in CIDR notation to use for the hosted master network.
     */
    master_ipv4_cidr_block?: pulumi.Input<string | undefined>;
    /**
     * Whether or not to enable GKE Auto-Monitoring. Supported values include: ALL, NONE
     */
    monitoring_auto_monitoring_config_scope?: pulumi.Input<string | undefined>;
    /**
     * Configuration for Managed Service for Prometheus. Whether or not the managed collection is enabled.
     */
    monitoring_enable_managed_prometheus?: pulumi.Input<boolean | undefined>;
    /**
     * Whether or not the advanced datapath metrics are enabled.
     */
    monitoring_enable_observability_metrics?: pulumi.Input<boolean | undefined>;
    /**
     * Whether or not the advanced datapath relay is enabled.
     */
    monitoring_enable_observability_relay?: pulumi.Input<boolean | undefined>;
    /**
     * List of services to monitor: SYSTEM_COMPONENTS, APISERVER, SCHEDULER, CONTROLLER_MANAGER, STORAGE, HPA, POD, DAEMONSET, DEPLOYMENT, STATEFULSET, KUBELET, CADVISOR, DCGM, and JOBSET. In beta provider, WORKLOADS is supported on top of those 12 values. (WORKLOADS is deprecated and removed in GKE 1.24.) KUBELET and CADVISOR are only supported in GKE 1.29.3-gke.1093000 and above. JOBSET is only supported in GKE 1.32.1-gke.1357001 and above. Empty list is default GKE configuration.
     */
    monitoring_enabled_components?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The monitoring metrics writer role to assign to the GKE node service account
     */
    monitoring_metric_writer_role?: pulumi.Input<string | undefined>;
    /**
     * The monitoring service that the cluster should write metrics to. Automatically send metrics from pods in the cluster to the Google Cloud Monitoring API. VM metrics will be collected by Google Compute Engine regardless of this setting Available options include monitoring.googleapis.com, monitoring.googleapis.com/kubernetes (beta) and none
     */
    monitoring_service?: pulumi.Input<string | undefined>;
    /**
     * The name of the cluster (required)
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The VPC network to host the cluster in (required)
     */
    network?: pulumi.Input<string | undefined>;
    /**
     * Enable network policy addon
     */
    network_policy?: pulumi.Input<boolean | undefined>;
    /**
     * The network policy provider.
     */
    network_policy_provider?: pulumi.Input<string | undefined>;
    /**
     * The project ID of the shared VPC's host (for shared vpc support)
     */
    network_project_id?: pulumi.Input<string | undefined>;
    /**
     * (Optional) - List of network tags applied to autopilot and auto-provisioned node pools.
     */
    network_tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Network tier configuration for the cluster
     */
    network_tier_config?: pulumi.Input<string | undefined>;
    /**
     * Specifies how node metadata is exposed to the workload running on the node
     */
    node_metadata?: pulumi.Input<string | undefined>;
    /**
     * List of maps containing node pools
     */
    node_pools?: pulumi.Input<pulumi.Input<{[key: string]: any}>[] | undefined>;
    /**
     * Map of strings containing cgroup node config by node-pool name
     */
    node_pools_cgroup_mode?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Map of strings containing hugepage size 1g config by node-pool name
     */
    node_pools_hugepage_size_1g?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Map of strings containing hugepage size 2m node config by node-pool name
     */
    node_pools_hugepage_size_2m?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Map of maps containing node labels by node-pool name
     */
    node_pools_labels?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: pulumi.Input<string>}>} | undefined>;
    /**
     * Map of maps containing linux node config sysctls by node-pool name
     */
    node_pools_linux_node_configs_sysctls?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: pulumi.Input<string>}>} | undefined>;
    /**
     * Map of maps containing node metadata by node-pool name
     */
    node_pools_metadata?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: pulumi.Input<string>}>} | undefined>;
    /**
     * Map of lists containing node oauth scopes by node-pool name
     */
    node_pools_oauth_scopes?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * Map of maps containing resource labels by node-pool name
     */
    node_pools_resource_labels?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: pulumi.Input<string>}>} | undefined>;
    /**
     * Map of maps containing resource manager tags by node-pool name
     */
    node_pools_resource_manager_tags?: pulumi.Input<{[key: string]: pulumi.Input<{[key: string]: pulumi.Input<string>}>} | undefined>;
    /**
     * Map of lists containing node network tags by node-pool name
     */
    node_pools_tags?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * Map of lists containing node taints by node-pool name
     */
    node_pools_taints?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<inputs.NodePoolsTaintsArgs>[]>} | undefined>;
    /**
     * Map of strings containing transparent hugepage defrag node config by node-pool name
     */
    node_pools_transparent_hugepage_defrag?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Map of strings containing transparent hugepage enabled node config by node-pool name
     */
    node_pools_transparent_hugepage_enabled?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * List of strings in CIDR notation that specify the IP address ranges that do not use IP masquerading.
     */
    non_masquerade_cidrs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The desired Pub/Sub topic to which notifications will be sent by GKE. Format is projects/{project}/topics/{topic}.
     */
    notification_config_topic?: pulumi.Input<string | undefined>;
    /**
     * Choose what type of notifications you want to receive. If no filters are applied, you'll receive all notification types. Can be used to filter what notifications are sent. Accepted values are UPGRADE_AVAILABLE_EVENT, UPGRADE_EVENT, and SECURITY_BULLETIN_EVENT.
     */
    notification_filter_event_type?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the Parallelstore CSI driver Addon is enabled for this cluster.
     */
    parallelstore_csi_driver?: pulumi.Input<boolean | undefined>;
    /**
     * The subnetwork to use for the hosted master network.
     */
    private_endpoint_subnetwork?: pulumi.Input<string | undefined>;
    /**
     * The project ID to host the cluster in (required)
     */
    project_id?: pulumi.Input<string | undefined>;
    /**
     * The Ray Operator Addon configuration for this cluster.
     */
    ray_operator_config?: pulumi.Input<inputs.RayOperatorConfigArgs | undefined>;
    /**
     * RBACBindingConfig allows user to restrict ClusterRoleBindings an RoleBindings that can be created.
     */
    rbac_binding_config?: pulumi.Input<inputs.RbacBindingConfigArgs | undefined>;
    /**
     * The region to host the cluster in (optional if zonal cluster / required if regional)
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * Whether is a regional cluster (zonal cluster if set false. WARNING: changing this after cluster creation is destructive!)
     */
    regional?: pulumi.Input<boolean | undefined>;
    /**
     * Projects holding Google Container Registries. If empty, we use the cluster project. If a service account is created and the `grant_registry_access` variable is set to `true`, the `storage.objectViewer` and `artifactregsitry.reader` roles are assigned on these projects.
     */
    registry_project_ids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The release channel of this cluster. Accepted values are `UNSPECIFIED`, `RAPID`, `REGULAR` and `STABLE`. Defaults to `REGULAR`.
     */
    release_channel?: pulumi.Input<string | undefined>;
    /**
     * Remove default node pool while setting up the cluster
     */
    remove_default_node_pool?: pulumi.Input<boolean | undefined>;
    /**
     * (Optional) - List of resource manager tags applied to autopilot and auto-provisioned node pools. A maximum of 5 tags can be specified. Tags must be in one of these formats: "tagKeys/{tag_key_id}"="tagValues/{tag_value_id}", "{org_id}/{tag_key_name}"="{tag_value_name}", "{project_id}/{tag_key_name}"="{tag_value_name}".
     */
    resource_manager_tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The ID of a BigQuery Dataset for using BigQuery as the destination of resource usage export.
     */
    resource_usage_export_dataset_id?: pulumi.Input<string | undefined>;
    /**
     * Security posture mode. Accepted values are `DISABLED` and `BASIC`. Defaults to `DISABLED`.
     */
    security_posture_mode?: pulumi.Input<string | undefined>;
    /**
     * Security posture vulnerability mode. Accepted values are `VULNERABILITY_DISABLED`, `VULNERABILITY_BASIC`, and `VULNERABILITY_ENTERPRISE`. Defaults to `VULNERABILITY_DISABLED`.
     */
    security_posture_vulnerability_mode?: pulumi.Input<string | undefined>;
    /**
     * The service account to run nodes as if not overridden in `node_pools`. The create_service_account variable default value (true) will cause a cluster-specific service account to be created. This service account should already exists and it will be used by the node pools. If you wish to only override the service account name, you can use service_account_name variable.
     */
    service_account?: pulumi.Input<string | undefined>;
    /**
     * The name of the service account that will be created if create_service_account is true. If you wish to use an existing service account, use service_account variable.
     */
    service_account_name?: pulumi.Input<string | undefined>;
    /**
     * Whether external ips specified by a service will be allowed in this cluster
     */
    service_external_ips?: pulumi.Input<boolean | undefined>;
    /**
     * The log_config for shadow firewall rules. You can set this variable to `null` to disable logging.
     */
    shadow_firewall_rules_log_config?: pulumi.Input<inputs.ShadowFirewallRulesLogConfigArgs | undefined>;
    /**
     * The firewall priority of GKE shadow firewall rules. The priority should be less than default firewall, which is 1000.
     */
    shadow_firewall_rules_priority?: pulumi.Input<number | undefined>;
    /**
     * The stack type to use for this cluster. Either `IPV4` or `IPV4_IPV6`. Defaults to `IPV4`.
     */
    stack_type?: pulumi.Input<string | undefined>;
    /**
     * Whether the Stateful HA Addon is enabled for this cluster.
     */
    stateful_ha?: pulumi.Input<boolean | undefined>;
    /**
     * Map of stub domains and their resolvers to forward DNS queries for a certain domain to an external DNS server
     */
    stub_domains?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * The subnetwork to host the cluster in (required)
     */
    subnetwork?: pulumi.Input<string | undefined>;
    /**
     * Timeout for cluster operations.
     */
    timeouts?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Specifies the total network bandwidth tier for NodePools in the cluster. Valid values are `TIER_UNSPECIFIED` and `TIER_1`. Defaults to `TIER_UNSPECIFIED`.
     */
    total_egress_bandwidth_tier?: pulumi.Input<string | undefined>;
    /**
     * If specified, the values replace the nameservers taken by default from the node’s /etc/resolv.conf
     */
    upstream_nameservers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of maps containing Windows node pools
     */
    windows_node_pools?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[] | undefined>;
    /**
     * The zones to host the cluster in (optional if regional cluster / required if zonal)
     */
    zones?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
