// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Module extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'modrandom:index:Module';

    /**
     * Returns true if the given object is an instance of Module.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Module {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Module.__pulumiType;
    }

    /**
     * my pet animal
     */
    public /*out*/ readonly pet!: pulumi.Output<string | undefined>;
    public /*out*/ readonly random_priority!: pulumi.Output<string | undefined>;
    public /*out*/ readonly random_seed!: pulumi.Output<string | undefined>;

    /**
     * Create a Module resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ModuleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["keeper_key"] = args ? args.keeper_key : undefined;
            resourceInputs["maxlen"] = args ? args.maxlen : undefined;
            resourceInputs["randseed"] = args ? args.randseed : undefined;
            resourceInputs["pet"] = undefined /*out*/;
            resourceInputs["random_priority"] = undefined /*out*/;
            resourceInputs["random_seed"] = undefined /*out*/;
        } else {
            resourceInputs["pet"] = undefined /*out*/;
            resourceInputs["random_priority"] = undefined /*out*/;
            resourceInputs["random_seed"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Module.__pulumiType, name, resourceInputs, opts, true /*remote*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Module resource.
 */
export interface ModuleArgs {
    /**
     * keeper key
     */
    keeper_key?: pulumi.Input<string>;
    maxlen?: pulumi.Input<number>;
    randseed?: pulumi.Input<string>;
}
