// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { CronTabArgs } from "./cronTab";
export type CronTab = import("./cronTab").CronTab;
export const CronTab: typeof import("./cronTab").CronTab = null as any;
utilities.lazyLoad(exports, ["CronTab"], () => require("./cronTab"));

export { CronTabListArgs } from "./cronTabList";
export type CronTabList = import("./cronTabList").CronTabList;
export const CronTabList: typeof import("./cronTabList").CronTabList = null as any;
utilities.lazyLoad(exports, ["CronTabList"], () => require("./cronTabList"));

export { CronTabPatchArgs } from "./cronTabPatch";
export type CronTabPatch = import("./cronTabPatch").CronTabPatch;
export const CronTabPatch: typeof import("./cronTabPatch").CronTabPatch = null as any;
utilities.lazyLoad(exports, ["CronTabPatch"], () => require("./cronTabPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:stable.example.com/v1:CronTab":
                return new CronTab(name, <any>undefined, { urn })
            case "kubernetes:stable.example.com/v1:CronTabList":
                return new CronTabList(name, <any>undefined, { urn })
            case "kubernetes:stable.example.com/v1:CronTabPatch":
                return new CronTabPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "stable.example.com/v1", _module)
