---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: podinfo
  values:
    ui:
      message: "Hello from ${cluster_name} (${cluster_env})"
      color: "#34577c"
