apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
    targetRevision: 9.1.3
    path: .
    helm:
      valueFiles:
      - $values/gitops/spoke/argocd/argocd-values.yaml
  - repoURL: https://github.com/pulumi/workshops
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
