// supply-chain-signing-as-code — 01-platform
//
// One `pulumi up` provisions everything step 1 of the demo needs: the AWS
// ECR repository images are pushed to, a `kind` cluster (kind has no native
// Pulumi provider, so it is driven through `@pulumi/command`'s local.Command),
// the Kyverno Helm chart, and the Kyverno ClusterPolicy that verifies
// Notation signatures at admission time.
//
// The ClusterPolicy embeds the certificate 00-signing-key/generate.sh
// produces. Run that script before this project's `pulumi up` — the
// certificate has to exist before the policy that reads it can be created.
import * as fs from "fs";
import * as path from "path";
import * as aws from "@pulumi/aws";
import * as command from "@pulumi/command";
import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();

// Pinned tool versions — see ../lib.sh and ../README.md for why each value
// was chosen and how it differs from the workshop brief's original figures.
const KYVERNO_CHART_VERSION = "3.9.1";
const KIND_NODE_IMAGE =
  "kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5";

const clusterName = config.get("clusterName") ?? "signing-demo";
const kindContext = `kind-${clusterName}`;
const repoName = config.get("ecrRepoName") ?? "supply-chain-signing-demo";

// The certificate path is relative to this project's directory by default
// (00-signing-key/generate.sh prints the exact value to set if the default
// identity or location changes).
const certPath = config.get("certPath") ?? "../00-signing-key/.notation/supply-chain-signing.demo.crt";
const resolvedCertPath = path.resolve(__dirname, certPath);
if (!fs.existsSync(resolvedCertPath)) {
  throw new Error(
    `Notation certificate not found at ${resolvedCertPath}. Run 00-signing-key/generate.sh first, ` +
      `then set config supply-chain-signing-platform:certPath if it printed a different path.`,
  );
}
const signingCert = fs.readFileSync(resolvedCertPath, "utf8");

// --- AWS ECR repository -----------------------------------------------------
//
// forceDelete lets `pulumi destroy` remove the repository even if images are
// still in it (08-teardown/ also explicitly deletes images first, since a
// tag pushed outside Pulumi's management is not always visible to it).
const repository = new aws.ecr.Repository("demo-repo", {
  name: repoName,
  forceDelete: true,
  imageTagMutability: "MUTABLE",
  imageScanningConfiguration: { scanOnPush: true },
});

// --- AWS Signer signing profile ----------------------------------------------
//
// Provisions the Notary Project + AWS Signer signing/verification policy the
// brief calls for, following the pattern in the Safeguard evidence cited in
// the workshop brief. The live demo signs with a local Notation test key
// (brief step 3), not this profile, because the brief's presenter setup
// deliberately avoids live key generation; this resource demonstrates that
// the AWS Signer path is provisioned as code and is the one an attendee
// would use in place of a local key outside the workshop.
const signingProfile = new aws.signer.SigningProfile("notation-signing-profile", {
  // Signer profile names allow letters, numbers and underscores only, so the
  // autogenerated hyphenated name would be rejected.
  name: "supply_chain_signing_demo",
  platformId: "Notation-OCI-SHA384-ECDSA",
});

// --- kind cluster, via a local command ---------------------------------------
//
// kind has no Pulumi provider, so a local.Command runs the CLI directly.
// Its `delete` runs only when this resource is destroyed (on `pulumi
// destroy`), matching the standard Pulumi CRUD lifecycle.
const renderDir = config.get("renderYamlToDirectory");
const kindCluster = new command.local.Command("kind-cluster", {
  create: pulumi.interpolate`kind get clusters | grep -qx "${clusterName}" || kind create cluster --name "${clusterName}" --image "${KIND_NODE_IMAGE}" --config "${__dirname}/kind-config.yaml"`,
  delete: pulumi.interpolate`kind delete cluster --name "${clusterName}" || true`,
  triggers: [clusterName, KIND_NODE_IMAGE],
});

// The kind context name is deterministic (`kind-<cluster name>`), so
// downstream resources do not need to wait on the command's output to know
// it — they still need `dependsOn: [kindCluster]` so Pulumi orders the
// cluster's creation before anything that talks to it.
//
// When `renderYamlToDirectory` is set (offline verification only — see
// README's Verification section), the Kubernetes provider renders YAML to a
// local directory instead of calling a live cluster; the provider rejects
// `context` and `renderYamlToDirectory` together, so exactly one is passed.
const k8sProvider = renderDir
  ? new k8s.Provider("kind", { renderYamlToDirectory: renderDir })
  : new k8s.Provider("kind", { context: kindContext }, { dependsOn: [kindCluster] });

// --- Kyverno -----------------------------------------------------------------
const kyvernoNamespace = new k8s.core.v1.Namespace(
  "kyverno",
  { metadata: { name: "kyverno" } },
  { provider: k8sProvider },
);

// helm.v4.Chart (not the older helm.v3.Release) so this project can also be
// verified with `renderYamlToDirectory` offline — v3.Release always shells
// out to a live Helm/cluster and cannot render to disk. Matches the pattern
// already established in defense-in-depth-kyverno-pulumi-policies/.
const kyvernoChart = new k8s.helm.v4.Chart(
  "kyverno",
  {
    chart: "kyverno",
    version: KYVERNO_CHART_VERSION,
    namespace: kyvernoNamespace.metadata.name,
    repositoryOpts: { repo: "https://kyverno.github.io/kyverno/" },
  },
  { provider: k8sProvider, dependsOn: [kyvernoNamespace] },
);

// Kyverno's ClusterPolicy-based verifyImages is marked deprecated in
// Kyverno's own current docs in favor of the CEL-based ImageValidatingPolicy,
// but remains documented and functional; see AGENTS.md for why this build
// still uses it (it matches the pattern the repo's other Kyverno workshop
// already established).
const imageVerificationPolicy = new k8s.apiextensions.CustomResource(
  "verify-notation-signature",
  {
    apiVersion: "kyverno.io/v2beta1",
    kind: "ClusterPolicy",
    metadata: { name: "verify-notation-signature" },
    spec: {
      webhookConfiguration: { failurePolicy: "Fail", timeoutSeconds: 30 },
      rules: [
        {
          name: "verify-signature-notary",
          match: { any: [{ resources: { kinds: ["Pod"] } }] },
          verifyImages: [
            {
              type: "Notary",
              imageReferences: [pulumi.interpolate`${repository.repositoryUrl}*`],
              failureAction: "Enforce",
              attestors: [
                {
                  count: 1,
                  entries: [{ certificates: { cert: signingCert } }],
                },
              ],
            },
          ],
        },
      ],
    },
  },
  { provider: k8sProvider, dependsOn: [kyvernoChart] },
);

export const repositoryUrl = repository.repositoryUrl;
export const clusterContext = kindContext;
export const clusterPolicyName = imageVerificationPolicy.metadata.name;
export const signingProfileName = signingProfile.name;
