apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-po
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://github.com/pulumi/workshops.git
    targetRevision: main
    directory:
      recurse: true
    path: pulumi-ultimate-gitops/gitops/teams/infra/kro-po/yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
