apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name }}
  description: Stack for ${{values.name }}
  annotations:
    pulumi.com/project-slug: ${{values.organization + "/" + values.name + "/" + values.stack}}
spec:
  owner: ${{values.owner}}
  type: service
  lifecycle: experimental
