// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Module extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'bucketmod:index:Module';

    /**
     * Returns true if the given object is an instance of Module.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Module {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Module.__pulumiType;
    }

    /**
     * The ARN of the bucket. Will be of format arn:aws:s3:::bucketname.
     */
    public /*out*/ readonly s3_bucket_arn!: pulumi.Output<string | undefined>;
    /**
     * The bucket domain name. Will be of format bucketname.s3.amazonaws.com.
     */
    public /*out*/ readonly s3_bucket_bucket_domain_name!: pulumi.Output<string | undefined>;
    /**
     * The bucket region-specific domain name. The bucket domain name including the region name, please refer here for format. Note: The AWS CloudFront allows specifying S3 region-specific endpoint when creating S3 origin, it will prevent redirect issues from CloudFront to S3 Origin URL.
     */
    public /*out*/ readonly s3_bucket_bucket_regional_domain_name!: pulumi.Output<string | undefined>;
    /**
     * The Route 53 Hosted Zone ID for this bucket's region.
     */
    public /*out*/ readonly s3_bucket_hosted_zone_id!: pulumi.Output<string | undefined>;
    /**
     * The name of the bucket.
     */
    public /*out*/ readonly s3_bucket_id!: pulumi.Output<string | undefined>;
    /**
     * The lifecycle rules of the bucket, if the bucket is configured with lifecycle rules. If not, this will be an empty string.
     */
    public /*out*/ readonly s3_bucket_lifecycle_configuration_rules!: pulumi.Output<any | undefined>;
    /**
     * The policy of the bucket, if the bucket is configured with a policy. If not, this will be an empty string.
     */
    public /*out*/ readonly s3_bucket_policy!: pulumi.Output<string | undefined>;
    /**
     * The AWS region this bucket resides in.
     */
    public /*out*/ readonly s3_bucket_region!: pulumi.Output<string | undefined>;
    /**
     * The domain of the website endpoint, if the bucket is configured with a website. If not, this will be an empty string. This is used to create Route 53 alias records.
     */
    public /*out*/ readonly s3_bucket_website_domain!: pulumi.Output<string | undefined>;
    /**
     * The website endpoint, if the bucket is configured with a website. If not, this will be an empty string.
     */
    public /*out*/ readonly s3_bucket_website_endpoint!: pulumi.Output<string | undefined>;
    /**
     * ARN of the directory bucket.
     */
    public /*out*/ readonly s3_directory_bucket_arn!: pulumi.Output<string | undefined>;
    /**
     * Name of the directory bucket.
     */
    public /*out*/ readonly s3_directory_bucket_name!: pulumi.Output<string | undefined>;

    /**
     * Create a Module resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ModuleArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["acceleration_status"] = args ? args.acceleration_status : undefined;
            resourceInputs["access_log_delivery_policy_source_accounts"] = args ? args.access_log_delivery_policy_source_accounts : undefined;
            resourceInputs["access_log_delivery_policy_source_buckets"] = args ? args.access_log_delivery_policy_source_buckets : undefined;
            resourceInputs["acl"] = args ? args.acl : undefined;
            resourceInputs["allowed_kms_key_arn"] = args ? args.allowed_kms_key_arn : undefined;
            resourceInputs["analytics_configuration"] = args ? args.analytics_configuration : undefined;
            resourceInputs["analytics_self_source_destination"] = args ? args.analytics_self_source_destination : undefined;
            resourceInputs["analytics_source_account_id"] = args ? args.analytics_source_account_id : undefined;
            resourceInputs["analytics_source_bucket_arn"] = args ? args.analytics_source_bucket_arn : undefined;
            resourceInputs["attach_access_log_delivery_policy"] = args ? args.attach_access_log_delivery_policy : undefined;
            resourceInputs["attach_analytics_destination_policy"] = args ? args.attach_analytics_destination_policy : undefined;
            resourceInputs["attach_deny_incorrect_encryption_headers"] = args ? args.attach_deny_incorrect_encryption_headers : undefined;
            resourceInputs["attach_deny_incorrect_kms_key_sse"] = args ? args.attach_deny_incorrect_kms_key_sse : undefined;
            resourceInputs["attach_deny_insecure_transport_policy"] = args ? args.attach_deny_insecure_transport_policy : undefined;
            resourceInputs["attach_deny_ssec_encrypted_object_uploads"] = args ? args.attach_deny_ssec_encrypted_object_uploads : undefined;
            resourceInputs["attach_deny_unencrypted_object_uploads"] = args ? args.attach_deny_unencrypted_object_uploads : undefined;
            resourceInputs["attach_elb_log_delivery_policy"] = args ? args.attach_elb_log_delivery_policy : undefined;
            resourceInputs["attach_inventory_destination_policy"] = args ? args.attach_inventory_destination_policy : undefined;
            resourceInputs["attach_lb_log_delivery_policy"] = args ? args.attach_lb_log_delivery_policy : undefined;
            resourceInputs["attach_policy"] = args ? args.attach_policy : undefined;
            resourceInputs["attach_public_policy"] = args ? args.attach_public_policy : undefined;
            resourceInputs["attach_require_latest_tls_policy"] = args ? args.attach_require_latest_tls_policy : undefined;
            resourceInputs["availability_zone_id"] = args ? args.availability_zone_id : undefined;
            resourceInputs["block_public_acls"] = args ? args.block_public_acls : undefined;
            resourceInputs["block_public_policy"] = args ? args.block_public_policy : undefined;
            resourceInputs["bucket"] = args ? args.bucket : undefined;
            resourceInputs["bucket_prefix"] = args ? args.bucket_prefix : undefined;
            resourceInputs["control_object_ownership"] = args ? args.control_object_ownership : undefined;
            resourceInputs["cors_rule"] = args ? args.cors_rule : undefined;
            resourceInputs["create_bucket"] = args ? args.create_bucket : undefined;
            resourceInputs["data_redundancy"] = args ? args.data_redundancy : undefined;
            resourceInputs["expected_bucket_owner"] = args ? args.expected_bucket_owner : undefined;
            resourceInputs["force_destroy"] = args ? args.force_destroy : undefined;
            resourceInputs["grant"] = args ? args.grant : undefined;
            resourceInputs["ignore_public_acls"] = args ? args.ignore_public_acls : undefined;
            resourceInputs["intelligent_tiering"] = args ? args.intelligent_tiering : undefined;
            resourceInputs["inventory_configuration"] = args ? args.inventory_configuration : undefined;
            resourceInputs["inventory_self_source_destination"] = args ? args.inventory_self_source_destination : undefined;
            resourceInputs["inventory_source_account_id"] = args ? args.inventory_source_account_id : undefined;
            resourceInputs["inventory_source_bucket_arn"] = args ? args.inventory_source_bucket_arn : undefined;
            resourceInputs["is_directory_bucket"] = args ? args.is_directory_bucket : undefined;
            resourceInputs["lifecycle_rule"] = args ? args.lifecycle_rule : undefined;
            resourceInputs["location_type"] = args ? args.location_type : undefined;
            resourceInputs["logging"] = args ? args.logging : undefined;
            resourceInputs["metric_configuration"] = args ? args.metric_configuration : undefined;
            resourceInputs["object_lock_configuration"] = args ? args.object_lock_configuration : undefined;
            resourceInputs["object_lock_enabled"] = args ? args.object_lock_enabled : undefined;
            resourceInputs["object_ownership"] = args ? args.object_ownership : undefined;
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["policy"] = args ? args.policy : undefined;
            resourceInputs["putin_khuylo"] = args ? args.putin_khuylo : undefined;
            resourceInputs["replication_configuration"] = args ? args.replication_configuration : undefined;
            resourceInputs["request_payer"] = args ? args.request_payer : undefined;
            resourceInputs["restrict_public_buckets"] = args ? args.restrict_public_buckets : undefined;
            resourceInputs["server_side_encryption_configuration"] = args ? args.server_side_encryption_configuration : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["transition_default_minimum_object_size"] = args ? args.transition_default_minimum_object_size : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["versioning"] = args ? args.versioning : undefined;
            resourceInputs["website"] = args ? args.website : undefined;
            resourceInputs["s3_bucket_arn"] = undefined /*out*/;
            resourceInputs["s3_bucket_bucket_domain_name"] = undefined /*out*/;
            resourceInputs["s3_bucket_bucket_regional_domain_name"] = undefined /*out*/;
            resourceInputs["s3_bucket_hosted_zone_id"] = undefined /*out*/;
            resourceInputs["s3_bucket_id"] = undefined /*out*/;
            resourceInputs["s3_bucket_lifecycle_configuration_rules"] = undefined /*out*/;
            resourceInputs["s3_bucket_policy"] = undefined /*out*/;
            resourceInputs["s3_bucket_region"] = undefined /*out*/;
            resourceInputs["s3_bucket_website_domain"] = undefined /*out*/;
            resourceInputs["s3_bucket_website_endpoint"] = undefined /*out*/;
            resourceInputs["s3_directory_bucket_arn"] = undefined /*out*/;
            resourceInputs["s3_directory_bucket_name"] = undefined /*out*/;
        } else {
            resourceInputs["s3_bucket_arn"] = undefined /*out*/;
            resourceInputs["s3_bucket_bucket_domain_name"] = undefined /*out*/;
            resourceInputs["s3_bucket_bucket_regional_domain_name"] = undefined /*out*/;
            resourceInputs["s3_bucket_hosted_zone_id"] = undefined /*out*/;
            resourceInputs["s3_bucket_id"] = undefined /*out*/;
            resourceInputs["s3_bucket_lifecycle_configuration_rules"] = undefined /*out*/;
            resourceInputs["s3_bucket_policy"] = undefined /*out*/;
            resourceInputs["s3_bucket_region"] = undefined /*out*/;
            resourceInputs["s3_bucket_website_domain"] = undefined /*out*/;
            resourceInputs["s3_bucket_website_endpoint"] = undefined /*out*/;
            resourceInputs["s3_directory_bucket_arn"] = undefined /*out*/;
            resourceInputs["s3_directory_bucket_name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Module.__pulumiType, name, resourceInputs, opts, true /*remote*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Module resource.
 */
export interface ModuleArgs {
    /**
     * (Optional) Sets the accelerate configuration of an existing bucket. Can be Enabled or Suspended.
     */
    acceleration_status?: pulumi.Input<string>;
    /**
     * (Optional) List of AWS Account IDs should be allowed to deliver access logs to this bucket.
     */
    access_log_delivery_policy_source_accounts?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * (Optional) List of S3 bucket ARNs which should be allowed to deliver access logs to this bucket.
     */
    access_log_delivery_policy_source_buckets?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * (Optional) The canned ACL to apply. Conflicts with `grant`
     */
    acl?: pulumi.Input<string>;
    /**
     * The ARN of KMS key which should be allowed in PutObject
     */
    allowed_kms_key_arn?: pulumi.Input<string>;
    /**
     * Map containing bucket analytics configuration.
     */
    analytics_configuration?: any;
    /**
     * Whether or not the analytics source bucket is also the destination bucket.
     */
    analytics_self_source_destination?: pulumi.Input<boolean>;
    /**
     * The analytics source account id.
     */
    analytics_source_account_id?: pulumi.Input<string>;
    /**
     * The analytics source bucket ARN.
     */
    analytics_source_bucket_arn?: pulumi.Input<string>;
    /**
     * Controls if S3 bucket should have S3 access log delivery policy attached
     */
    attach_access_log_delivery_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have bucket analytics destination policy attached.
     */
    attach_analytics_destination_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should deny incorrect encryption headers policy attached.
     */
    attach_deny_incorrect_encryption_headers?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket policy should deny usage of incorrect KMS key SSE.
     */
    attach_deny_incorrect_kms_key_sse?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have deny non-SSL transport policy attached
     */
    attach_deny_insecure_transport_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should deny SSEC encrypted object uploads.
     */
    attach_deny_ssec_encrypted_object_uploads?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should deny unencrypted object uploads policy attached.
     */
    attach_deny_unencrypted_object_uploads?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have ELB log delivery policy attached
     */
    attach_elb_log_delivery_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have bucket inventory destination policy attached.
     */
    attach_inventory_destination_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have ALB/NLB log delivery policy attached
     */
    attach_lb_log_delivery_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should have bucket policy attached (set to `true` to use value of `policy` as bucket policy)
     */
    attach_policy?: pulumi.Input<boolean>;
    /**
     * Controls if a user defined public bucket policy will be attached (set to `false` to allow upstream to apply defaults to the bucket)
     */
    attach_public_policy?: pulumi.Input<boolean>;
    /**
     * Controls if S3 bucket should require the latest version of TLS
     */
    attach_require_latest_tls_policy?: pulumi.Input<boolean>;
    /**
     * Availability Zone ID or Local Zone ID
     */
    availability_zone_id?: pulumi.Input<string>;
    /**
     * Whether Amazon S3 should block public ACLs for this bucket.
     */
    block_public_acls?: pulumi.Input<boolean>;
    /**
     * Whether Amazon S3 should block public bucket policies for this bucket.
     */
    block_public_policy?: pulumi.Input<boolean>;
    /**
     * (Optional, Forces new resource) The name of the bucket. If omitted, Terraform will assign a random, unique name.
     */
    bucket?: pulumi.Input<string>;
    /**
     * (Optional, Forces new resource) Creates a unique bucket name beginning with the specified prefix. Conflicts with bucket.
     */
    bucket_prefix?: pulumi.Input<string>;
    /**
     * Whether to manage S3 Bucket Ownership Controls on this bucket.
     */
    control_object_ownership?: pulumi.Input<boolean>;
    /**
     * List of maps containing rules for Cross-Origin Resource Sharing.
     */
    cors_rule?: any;
    /**
     * Controls if S3 bucket should be created
     */
    create_bucket?: pulumi.Input<boolean>;
    /**
     * Data redundancy. Valid values: `SingleAvailabilityZone`
     */
    data_redundancy?: pulumi.Input<string>;
    /**
     * The account ID of the expected bucket owner
     */
    expected_bucket_owner?: pulumi.Input<string>;
    /**
     * (Optional, Default:false ) A boolean that indicates all objects should be deleted from the bucket so that the bucket can be destroyed without error. These objects are not recoverable.
     */
    force_destroy?: pulumi.Input<boolean>;
    /**
     * An ACL policy grant. Conflicts with `acl`
     */
    grant?: any;
    /**
     * Whether Amazon S3 should ignore public ACLs for this bucket.
     */
    ignore_public_acls?: pulumi.Input<boolean>;
    /**
     * Map containing intelligent tiering configuration.
     */
    intelligent_tiering?: any;
    /**
     * Map containing S3 inventory configuration.
     */
    inventory_configuration?: any;
    /**
     * Whether or not the inventory source bucket is also the destination bucket.
     */
    inventory_self_source_destination?: pulumi.Input<boolean>;
    /**
     * The inventory source account id.
     */
    inventory_source_account_id?: pulumi.Input<string>;
    /**
     * The inventory source bucket ARN.
     */
    inventory_source_bucket_arn?: pulumi.Input<string>;
    /**
     * If the s3 bucket created is a directory bucket
     */
    is_directory_bucket?: pulumi.Input<boolean>;
    /**
     * List of maps containing configuration of object lifecycle management.
     */
    lifecycle_rule?: any;
    /**
     * Location type. Valid values: `AvailabilityZone` or `LocalZone`
     */
    location_type?: pulumi.Input<string>;
    /**
     * Map containing access bucket logging configuration.
     */
    logging?: any;
    /**
     * Map containing bucket metric configuration.
     */
    metric_configuration?: any;
    /**
     * Map containing S3 object locking configuration.
     */
    object_lock_configuration?: any;
    /**
     * Whether S3 bucket should have an Object Lock configuration enabled.
     */
    object_lock_enabled?: pulumi.Input<boolean>;
    /**
     * Object ownership. Valid values: BucketOwnerEnforced, BucketOwnerPreferred or ObjectWriter. 'BucketOwnerEnforced': ACLs are disabled, and the bucket owner automatically owns and has full control over every object in the bucket. 'BucketOwnerPreferred': Objects uploaded to the bucket change ownership to the bucket owner if the objects are uploaded with the bucket-owner-full-control canned ACL. 'ObjectWriter': The uploading account will own the object if the object is uploaded with the bucket-owner-full-control canned ACL.
     */
    object_ownership?: pulumi.Input<string>;
    /**
     * Bucket owner's display name and ID. Conflicts with `acl`
     */
    owner?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * (Optional) A valid bucket policy JSON document. Note that if the policy document is not specific enough (but still valid), Terraform may view the policy as constantly changing in a terraform plan. In this case, please make sure you use the verbose/specific version of the policy. For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide.
     */
    policy?: pulumi.Input<string>;
    /**
     * Do you agree that Putin doesn't respect Ukrainian sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!
     */
    putin_khuylo?: pulumi.Input<boolean>;
    /**
     * Map containing cross-region replication configuration.
     */
    replication_configuration?: any;
    /**
     * (Optional) Specifies who should bear the cost of Amazon S3 data transfer. Can be either BucketOwner or Requester. By default, the owner of the S3 bucket would incur the costs of any data transfer. See Requester Pays Buckets developer guide for more information.
     */
    request_payer?: pulumi.Input<string>;
    /**
     * Whether Amazon S3 should restrict public bucket policies for this bucket.
     */
    restrict_public_buckets?: pulumi.Input<boolean>;
    /**
     * Map containing server-side encryption configuration.
     */
    server_side_encryption_configuration?: any;
    /**
     * (Optional) A mapping of tags to assign to the bucket.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The default minimum object size behavior applied to the lifecycle configuration. Valid values: all_storage_classes_128K (default), varies_by_storage_class
     */
    transition_default_minimum_object_size?: pulumi.Input<string>;
    /**
     * Bucket type. Valid values: `Directory`
     */
    type?: pulumi.Input<string>;
    /**
     * Map containing versioning configuration.
     */
    versioning?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Map containing static web-site hosting or redirect configuration.
     */
    website?: any;
}
