---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-dev-world-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:pulumi:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: default
  name: pulumi
- kind: ServiceAccount
  namespace: default
  name: pulumi-dev-world-sa
---
apiVersion: pulumi.com/v1
kind: Program
metadata:
  name: pu-program-dev-world
program:
  packages:
    talos-go-component: https://github.com/dirien/pulumi-talos-go-component@0.0.0-x5ed2a9a45c6d287bd2485f4db1e8c052b164a5ef
  resources:
    app:
      type: digitalocean:App
      properties:
        spec:
          name: app-dev-world
          region: lon1
          services:
          - name: app-service-dev-world
            instanceCount: 1
            instanceSizeSlug: "apps-s-1vcpu-1gb"
            git:
              repoCloneUrl: https://github.com/digitalocean/sample-golang.git
              branch: "main"
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pu-stack-dev-world
spec:
  serviceAccountName: pulumi-dev-world-sa
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-operator-secrets
        key: pulumi-access-token
    DIGITALOCEAN_TOKEN:
      secret:
        name: pulumi-operator-secrets
        key: do-token
      type: Secret
  programRef:
    name: pu-program-dev-world
  stack: ediri/pu-program-dev-world/dev
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.180.0-nonroot
