// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { TalosClusterArgs } from "./talosCluster";
export type TalosCluster = import("./talosCluster").TalosCluster;
export const TalosCluster: typeof import("./talosCluster").TalosCluster = null as any;
utilities.lazyLoad(exports, ["TalosCluster"], () => require("./talosCluster"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "talos-go-component:talos:TalosCluster":
                return new TalosCluster(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("talos-go-component", "talos", _module)
